version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.10.4
    - 3.10.6
    - 3.4.0
    - 3.4.1
    - 3.4.2
    - 3.5.0
    - 3.5.1
    - 3.5.3
    - 3.6.0
    - 3.6.1
    - 3.6.5
    - 3.6.6
    - 3.6.7
    - 3.8.1
    - 3.8.2
    - 3.9.0
    - 3.9.1
    - 3.9.2
    - 3.9.3
    - 4.0.0
    - 4.0.1
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.5
    - 4.1.7
    - 4.1.8
    - 4.1.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.26
    - 14.14.29
    - 14.14.32
    - 14.14.33
    - 14.14.36
    - 15.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.0
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.16
  - dependency-name: next
    versions:
    - 10.1.0
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
  - dependency-name: react-dom
    versions:
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.15.0
    - 4.15.2
    - 4.16.0
    - 4.16.1
    - 4.18.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.0
    - 7.13.5
    - 7.13.9
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.15.0
    - 4.16.0
    - 4.16.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.2
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.0
    - 12.0.1
  - dependency-name: prismjs
    versions:
    - 1.22.0
  - dependency-name: prettier
    versions:
    - 2.2.1
